### ISSUE TITLE
Passkey Support?

### ISSUE THREAD

**Issue by charkour** [workos/authkit#10]
Hi there,

This project looks fantastic. On the marketing site, it says it supports "biometric and passkey auth" but I cannot find information about this on the documentation. 

Do you support "biometric and passkey auth"?

Thank you

<img width="338" alt="image" src="https://github.com/workos/authkit/assets/33156025/ef3fa73e-1e5f-478d-922d-1522bd93ec85">

**Comment by benoitgrelard** [comment]
Hey @charkour,

Passkey support is coming soon. Is it a blocking feature for you? We’d love to learn more about your use case if you’re open to it.

**Comment by grinich** [comment]
It will. :)

**Comment by ragnorc** [comment]
@benoitgrelard What do you think the ETA is for this?

**Comment by benoitgrelard** [comment]
@ragnorc we do not currently have an ETA for this, I will be sure to update when we do.

**Comment by ragnorc** [comment]
Thank you @benoitgrelard!

**Comment by CodeWithShreyans** [comment]
update on this?

**Comment by nkhine** [comment]
https://workos.com/docs/user-management/passkeys

Looks like it is now supported

**Comment by PaulAsjes** [comment]
Correct, this has shipped and is now available to everyone.
