### ISSUE TITLE
Github OAuth Support

### ISSUE THREAD

**Issue by leifu1128** [workos/authkit#15]
Would be nice for those of us making devtools.

**Comment by benoitgrelard** [comment]
Hey @leifu1128 I have some good news for you. It is coming soon 🙂 Likely this month! Keep an eye on https://workos.com/changelog and follow [@authkit](https://twitter.com/authkit) on X.

**Comment by benoitgrelard** [comment]
Hey @leifu1128 this is now shipped 🙂

https://workos.com/changelog/github-oauth-support

**Comment by leifu1128** [comment]
Wow, that was fast. Thanks!
