### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by corysimmons** [workos/authkit#19]
I'm having a hard time seeing what the prebuilt UI looks like. I can see the login form on authkit.com, but that's it. I can't find screenshots of stuff like the Clerk avatar dropdown or profile modal. The widgets are [front-and-center](https://clerk.com/_next/image?url=%2Fimages%2Fhome%2Fnew-hero.png&w=3840&q=75) on the Clerk website. I'd hope to at least see the screenshots on the README.

I don't want to have to create an account and set up all the example code just to see if I like the UI enough to switch from Clerk. :)

**Comment by benoitgrelard** [comment]
Hey @corysimmons that's a good idea, thanks for posting the issue. We'll look into it!
