### ISSUE TITLE
API support on Cloudflare Pages / Workers?

### ISSUE THREAD

**Issue by houmark** [workos/authkit#23]
Hey there,

I'm developing Remix apps on Cloudflare Pages and it does not look like Authkit supports that (workos/node seems to be using plenty of node core libs, and axios for fetching).

Do you have any plans to support Cloudflare Pages / Workers? If so, do you have a timeline? I'm happy to participate in testing :)

**Comment by benoitgrelard** [comment]
Yes we do! We have a stream of work planned for making the node SDK (should it be renamed to JS SDK? 😀) to work in workers. I cannot comment on timeline yet but will update you when I know more.

**Comment by houmark** [comment]
Sounds great. Looking forward to that. And yes, a rename would certainly make it more clear that this is compatible with more runtimes than just Node :)

**Comment by benoitgrelard** [comment]
Hey @houmark, I wanted to give you a quick update on this.
It's coming along nicely and I have just opened a PR: https://github.com/workos/workos-node/pull/962

**Comment by houmark** [comment]
Hey @benoitgrelard it sure does look like you're making fast progress on this.

Does that mean this could make it to either public beta or release within the next 4-6 weeks — or can you speak to a specific timeline?

**Comment by benoitgrelard** [comment]
Hey, I have actually already published a release candidate of the SDK on npm ([6.0.0-rc.1](https://www.npmjs.com/package/@workos-inc/node/v/6.0.0-rc.1) tagged next)
It can be installed with `npm install @workos-inc/node@next`

**Comment by houmark** [comment]
That's very cool! I really appreciate the updates here and the "early access".

I spent a few hours tonight, playing around with the release candidate in Remix, headless, using actions/loaders to sign up and load the user data. Still didn't test all around, but everything works very smooth so far, so that's very cool.

I do have one unrelated question, but I thought I'd give it a shot, it worked out well the last time :)

I've worked quite a lot with AWS Cognito, and they have "user groups" as a concept. I don't see that in Authkit, but in some docs I found `user.groups` as an array on a Profile in an Organization, but couldn't find anymore on that. Are organizations a more advanced edition of groups from Cognito?

I'd like to be able to assign users into groups so that I can handle access to sub-features based on the group(s) they are a part of — or another simple role handling without too much overhead. Organizations seem a bit complex to deal with for a simpler use case.

**Comment by benoitgrelard** [comment]
[v6.0.0](https://www.npmjs.com/package/@workos-inc/node/v/6.0.0) has now been released and adds support for cloudflare workers / edge runtimes.

**Comment by benoitgrelard** [comment]
@houmark 

> I've worked quite a lot with AWS Cognito, and they have "user groups" as a concept. I don't see that in Authkit, but in some docs I found user.groups as an array on a Profile in an Organization, but couldn't find anymore on that. Are organizations a more advanced edition of groups from Cognito?

> I'd like to be able to assign users into groups so that I can handle access to sub-features based on the group(s) they are a part of — or another simple role handling without too much overhead. Organizations seem a bit complex to deal with for a simpler use case.

Organizations typically correspond 1:1 with your customers, or 1:1 with IT departments for larger enterprises.
AuthKit doesn't yet pass through group information from Cognito, but we have some very good news coming next month for mapping IdP groups into Roles.

Stay tuned!

**Comment by houmark** [comment]
Awesome this is now released in stable. I've played around a bit more on RC2 since, and it's been stable for me both in the development environment and deployed to Cloudflare.

I know this is not the right place for these questions, but I wonder where that is. In any case, I'm not looking to migrate an existing Cognito user pool at this time, I was merely comparing features and how to attack handling access to different features for a customer or a group of customers. I've since read up a bit more on Organizations, and it looks like a powerful feature, but also not particularly adequate for simple role/feature access, hence why I was looking for the possibility of attaching specific groups on a user, in a similar fashion as how Cognito does this.

That does not seem possible a this time. Does that mean that handling roles/groups is pushed back on us to implement inside our platform and then combine the user with some internal access control for different parts of our platform? It feels like this should be something the auth platform should handle for us so we don't need to maintain two `User` objects.

The simplest implementation of this would be a groups object in WorkOS/AuthKit and the possibility to attach a user to `n` groups and have that exposed as an array (just like it is on Organization → Profile → groups). This enables you to do pretty simple access control to parts of your platform with little administration/overhead.

On a related note, having meta tags (Cognito also have this) on a user where you can add a few key/value pairs would also be very useful (again to avoid having to have pretty much any user information in our DB).

This sounds a bit like a love story to Cognito. It's not, I've had my fair share of annoyances with that platform, but Cognito is one of the larger adopted platforms out there, so I would assume you could see a lot of people trying out your platform, coming from Cognito in the future, which means feature compatibility would easy that adoption/transition.

Re-reading your response once again, it seems like most of my requests above should be coming fairly soon to the basic core AuthKit platform (without the use of SSO)?

**Comment by benoitgrelard** [comment]
>  I've since read up a bit more on Organizations, and it looks like a powerful feature, but also not particularly adequate for simple role/feature access, hence why I was looking for the possibility of attaching specific groups on a user, in a similar fashion as how Cognito does this.

For now yes, however as I said we have some upcoming updates in the coming weeks that will have a positive impact here, so stay tuned for this.

> I know this is not the right place for these questions, but I wonder where that is.

I would definitely recommend emailing our support ([support@workos.com](mailto:support@workos.com)) with any questions you may have!
